### ISSUE TITLE
I have an issue with an auto-mute keyword, and a small suggestion.

### ISSUE THREAD

**Issue by TheInfamousAlk** [CreeperHost/CreeperHostGui#131]
I was in the Mine together chat when someone said the word "boomer", as in "baby boomer", which describes the set of people born between 1946 and 1964. They were auto-muted because of this. The discussion happening was in no way disrespectful or toxic towards anyone. I myself am a "boomer", and I understand that the auto-mute was because "okay boomer" is thought by some to be derogatory. 

I disagree. I think "okay boomer" is used by some to discredit the opinions of old people in general, whether or not they are a baby boomer. 

The reasons I think this should not be an auto-mute are as follows. 
1. It is used in normal discussion all the time, whether that is talking about actual generations in a polite manner, talking about left 4 dead 2, or any other topic that the word "boomer" could come up. 
2. "Okay boomer" is a meme. It's not a hate slur. It's not a cuss word. People who use it seriously will be disrespecting old people and discrediting their opinions whether or not they can use the word boomer. Banning the word will not stop these people, it will only make them change their wording in their attempt to be toxic. 
3. In my experience, the word boomer (and in many cases, "okay boomer") is used in a non-toxic, friendly manner, whether they're just memeing or talking about baby boomers. It's very rarely used in an actually toxic manner. I use this phrase, and I'm a baby boomer. 

I am not sure who decided boomer was bad enough to auto-mute it, but I request, as an active mine together user, that a thoughtful discussion to reconsider this decision takes place.

**Comment by Draylynn** [comment]
"Okay Boomer" **is** by very definition, ageist discrimination. It is more and more being used as a negative term. Just because people find it funny doesn't make it right.
At one time or another in Earth's history the N-word was also considered completely appropriate... Still didn't make it right. Discrimination is discrimination.

As such a decision was made to have it filtered: And those who try to work around that, will be breaking chat rules, not just for using the phrase, but for showing undue etiquette for the chat and the rules - We do have mods who actively monitor and check back the chat to make sure everything is hunky dory.
Toxic players will and do get banned, which is why it's such a nice place to chat.

We're sorry if you do not agree with this, but this is the law of MineTogether.

**Comment by TheInfamousAlk** [comment]
Well, thanks for hearing me out, and I'll respect the decision to ban this word. Hope y'all have a good rest of your day.
