### ISSUE TITLE
Ban Appeal 12/3/19

### ISSUE THREAD

**Issue by TheYeti** [CreeperHost/CreeperHostGui#137]
I am now aware of why I was banned.  I completely messed up, didn't even think about the image being anything other than explaining a reference or how it was NSFW thus age inappropriate.  Attempted to appeal the ban in a previous issue but it was immediately locked with no mention of a duration for the ban or if it can even be appealed.  I completely own the fact that I messed up.  

Ban ID: 5de6221bdab5f5-03643556
Unique Code: LXfa-kvcK

**Comment by Draylynn** [comment]
The issue is resolved:
You admit breaking a rule... That doesn't give automatic grounds for the ban to be reversed.

Bans are usually permanent or until someone clears the ban list in some new feature update or what not, which has happened once in the years MT's been running.
Your ban at this time is behind upheld.

**Comment by TheYeti** [comment]
I'm attempting to apologize for breaking said rule.  People make mistakes.  I admit that I made one by not paying attention to what I was posting.

**Comment by CH-Paul-T** [comment]
Please do not harass us on an issue tracker.
