### ISSUE TITLE
Banned

### ISSUE THREAD

**Issue by desmondthemonbear** [CreeperHost/CreeperHostGui#148]
I was Recently banned for cursing on MineTogether. Now I know its dumb but realistically my own fault. I cursed, I understand completely why the ban was dealt. however me being a dumb dumb I didn't fully read the rules of MineTogether. If you deem myself unbannable I will not be using profanities or curses, or doing anything to upset the system anymore.

Ban ID: mtg-ban=5e09f36378fde3-22984687

Upon checking the logs you will see directly after that I immediately apologize.
I apologize for any inconvenience this has caused. I would just like to be able to chat with minecrafters from different parts of the world again.

Thank you for your consideration, Have a wonderful day.

**Comment by Draylynn** [comment]
Your user has been unbanned...
_This isn't COD, there is an age rating on Minecraft which should be abided in any public communication without explicit rules stating otherwise._
New years resolution: Treat public chat-rooms like there may be kids present, because there often are. No swearing, set a good example; to lead by example is to shape the minds of future generations to come.

Happy new year.
NOTE: You may need to restart the client to reconnect to chat.

**Comment by desmondthemonbear** [comment]
I appreciate the second chancce, it will not be wasted
