### ISSUE TITLE
[Suggestion] Report server button

### ISSUE THREAD

**Issue by aaronhowser1** [CreeperHost/CreeperHostGui#155]
![](https://cdn.discordapp.com/attachments/392388786366971914/668010686017961985/unknown.png)

I noticed this server has 69420 player slots, which (while being epic meme) is a bit inappropriate. I don't really think that specifically is important, but it brought to mind that there isn't really a way to report server list abuse, or report public list servers that have abusive admins or whatever.

**Comment by CH-Paul-T** [comment]
Hey Aaron,

Originally, it was decided that we'd not moderate these due to the chance of being accused of bias.

I'll review that policy though with the team over the next week or so and see where we go from there.

It's not really set up in a way we can block a specific server right now, so we'd need to do some actual work.

Paul

**Comment by ThePaul-T** [comment]
At the moment, I think we want to remain neutral on the server front (May change in the near future, as I have given Gaz a task, once that is done we may have access to people who I'd not view as being seen as having bias).

My literal reason for this is, as a server provider, if we start moderating what servers are allowed on there, we can be seen as having bias towards our own customers.

So our current "moderation" technique is if Mojang don't stop them, we won't. It's not my ideal choice, but until our current plans pan out, there's nothing we can do to change the perception of bias.
