### ISSUE TITLE
[Suggestion] Ability to show minecraft console information along with MineTogether chat.

### ISSUE THREAD

**Issue by Iamthedogev** [CreeperHost/CreeperHostGui#179]
I came across this when I was using the fluxbore from thermal innovation. The fluxbore can switch modes on the fly to change how big of an area you can mine with it, but you can only see the text that says what mode you are on if you are in the commands tab. With the feature being intended to be able to adapt your mining area to the task at hand, it is very disruptive to have to switch to the commands tab just to see what mode you are on and would be nice to be able to see it even if you still had to switch back to the commands tab to enter in any commands.

**Comment by gigabit101** [comment]
This would not be something that could be done easily due to us not having a way to know what the message is and why it was sent for example we could make it switch the chats if a message entered the default chat but this would trigger for any message and would become annoying very quickly.

We will, however, think about adding an API to allow other mods to switch the tabs or add the message into our chat.
