### ISSUE TITLE
Unban Appeal

### ISSUE THREAD

**Issue by xHypno-Klaus** [CreeperHost/CreeperHostGui#240]
I Was Banned Today For (I Think) Saying The Title Of A Song In Chat.

I Can See How I Could Be Taken The Wrong Way Due To The Name Of The Song, But I'd Like To Request To Be Unbanned. I Did Not Know That It Could Get Me Into Trouble And I Apologize. 

https://imgur.com/a/LgdGeMg

**Comment by Draylynn** [comment]
5ea30b82a40881-67997144...
Inappropriate Content...

You were mentioning several rap videos (quite frankly, such horrible rapping that I had to lookup the lyrics, because it was about to make my ears bleed) containing words such as 'f***, s***, bi****', glorifying abuse of women, drug use, and, containing racial slurs.

On what planet do you think that is appropriate in a public chatroom for a low-age rated game with young kids in it.

![image](https://user-images.githubusercontent.com/45239550/80249433-b84d8e80-8669-11ea-96a9-dd72ac09ec77.png)
