### ISSUE TITLE
Ban appeal

### ISSUE THREAD

**Issue by Spo0on12345** [CreeperHost/CreeperHostGui#267]
I got muted for saying roblox once and tried to evade the filter on the same word after getting warned once which i forgot because it was like 1 hour later ending up me getting muted for 10 minutes then 5 minutes later getting banned. I don't understand why i got banned for saying Roblox and i don't get why roblox is a inappropiate word to say. My username is Spo0on12345, i didn't screenshot the ban message because i relaunched the game after. i request for a ban appeal because this isn't really worth a ban.

**Comment by Draylynn** [comment]
"If a word is on the mute list or ban list, you do **not** obfuscate or repeat it."
You were also told not to lure others into the mute, yet you continually tried to.

Roblox is on the list as a 'funny', but then you started poking fun at the mute list and also luring them into it with derogatory terms.

"Next one to filter evade gets banned. Type "Rules" to see the chat rules".
You got banned for repeatedly ignoring my warnings, filter evasion and wheaton's law.

**Comment by Draylynn** [comment]
1:25pm you were muted for it.
1:38pm, Draylynn: "A) Luring people into the filter is against Wheaton's Law. B) The filters there for a reason. C) Due to poor moderation and enforcement of their game rating: Roblox is not an appropriate game to talk about in here."
2:09pm: "btw guys dont say booomer"
2:12pm, Draylynn: "If you know a word is mutable/bannable in here, you don't obfuscate it from the bot, you simply just don't say it."
"Next one to filter evade gets banned. Type "rules" to see the chat rules."
3:35PM: "do you know how to spell robloxx?"
... Ahh fudge, here we go again.

You saw the warnings, you even responded to them. You were informed why it was banned, 90% of the time, the topics turn adult when that game is mentioned, because the game is widely misused against it's rating.
_As chat moderators, it's our job to weed out the toxic, inappropriate users and keep the chat on topic and within the content rules of the game (ESRB10+)._

Your behaviour is unacceptable, you showed no consideration for the rules, the other users, or the chat moderators, to the point it felt like you were purposely going out your way to push my buttons and test the limits of chat... Rather than just behaving, making friends and discussing Minecraft.

You're banned for filter evasion, abreach of Wheaton's Law, and apparently, just not 'getting it'.

**Comment by Starcloak** [comment]
Curious.  Wanna hear the comment that got me banned?  Of course you don’t.  Here it is anyway:

“Lemme put it this way.  I believe that two, gay, interracial men should be allowed to protect their weed farms with semi-automatic machine guns while waving whatever flag they want, than to have some tech overlord decide their lives for them.”


Fair.  Okay, aside from the fact that immediately I recognized that semi-automatic rifles and fully-automatic machine guns are two, far different things (Get outta my head, CNN), that is the single most inclusive message that I’ve ever sent to anyone in my life.  
Curious.  Someone please, tell me how that’s in any way, vulgar, non-PC, or in some way outside of the realm of the language and tact that the average 4th-grader (10-y-o), talks or behaves?
Honest.  It’s probably above a 4th-grader’s level of thinking (which today, is comprised mostly of insults anyways), and is probably the most inclusive, PC, anti-inflamatory thing I’ve ever sent to anybody.
Serious.  I’m not even joking.  Plz send help.  Does not compute.
