### ISSUE TITLE
Banned for "Questioning Mods" ??

### ISSUE THREAD

**Issue by justluna** [CreeperHost/CreeperHostGui#294]
**Minecraft Username:** 
discordlunaa
**Ban ID:**
mtg-ban=5f1264e5176020-47525906
**What was the reason for your ban?** 
Not sure, I'm led to believe it was for questioning mods due to what was said in chat, the reason stated in the ban is "Kicked - Nope [Ban ID: **Ban ID**]
Here is what I said in chat.
![image](https://user-images.githubusercontent.com/68453682/87843419-616ee400-c869-11ea-9325-998e39f8a101.png)

**Why you think you should be unbanned:**

- I had no intentions of causing trouble nor could I have ever guessed that this is a bannable offense. I would check the rules for this but I can't find the rules now that I am banned.

- I have seen people call MineTogether's chat filter "trash" because someone was muted for saying the S word, and they received no punishment.

- I got an insanely harsh punishment considering people often cuss and only get a mute.

- MineTogether is hosted by a professional company that should be able to take criticism like this. I don't know if the staff member in question was acting out of emotion due to what I said or if this is actually written in the rules; that you should not comment on how easy it is to get banned, OR if you guys just get an alert when someone says key words like "ban" in chat and whoever saw that instantly banned me without looking into the situation further. Regardless, very unjust ban in my opinion.

**Some other information about the incident:**
The dude who got banned before me made a joke telling me to "pull a hitler and kill myself" and since I wasn't offended by what he told me I tried to get him to not be banned. I completely understand his ban however, and wasn't planning on making it a big deal or cause any issues with your staff team. What I said in chat was me simply making a statement on how easy it is to get banned if you're not careful. I don't see how me saying that is at all worthy of a ban. The point I was making was that we have to be careful in order to not be banned which is something I could see a moderator saying. It's a warning of sorts.

**What steps will you take to make sure this doesn't happen in the future:**
Read the rules more carefully. I didn't think you could be banned for something as ridiculous as this.

**Comment by Draylynn** [comment]
- "The dude who _then_ responded to _my_ baited Hitler comment"... Fixed.
- You didn't include the screenshot of what you said... Intentional mis-redirection?
- Some words are insta-banned, some are just muted because they're less offensive or have other meanings.
- You were banned for the warcrimes comment, not your criticism. 

But hey, walking into a chat full of undisciplined kids who can't help themselves and baiting them with comments like that is totally acceptable, right? This isn't your first brush with the rules either, having seen people hit the word filter, you've also previously been caught incorrectly repeating (boomer) it 'for funsies' and getting muted.

The rules are displayed on joining chat, if you've already been shown them before, then you're told to type "rules" to display them at the top of chat.
This is a mod for Minecraft, an ESRB10+ rated game and it's a **public chatroom**, not Reddit, not 4Chan, not some random forum, you should watch what you say in front of minors and set a good example, namely by not making light of such horrible topics which shouldn't even be in the Minecraft gaming channel.

Come back in a month or so, when you know how to behave in a children's chatroom/public, and try again.
