### ISSUE TITLE
I was stupid and would like to be unbanned

### ISSUE THREAD

**Issue by BaconShrub** [CreeperHost/CreeperHostGui#312]
**Minecraft Username:** 

BaconShrub

**Ban ID:**

mtg-ban=5f25b321a11cb8-60196294

**What was the reason for your ban?** 

It says Wheaton's Law.

**Why you think you should be unbanned:**

I don't actually understand why I was banned when I was the one who legitimately removed myself from a hostile conversation, and Muted the other players involved so that it couldn't continue. 

**What steps will you take to make sure this doesn't happen in the future:**

I believe what I said above was the right thing to do, but I was banned anyway. I do not understand what else I could have done under the circumstances. I did not do anything wrong.

**Comment by Draylynn** [comment]
You were removed because you simply wouldn't drop the whole crafting discussion.

"I don't have the time or inclination to fight over such a subjective thing as taste": But then you kept going and going, and going, and even worse, you did this in front of Paul_T. You started calling users names. When you were told to stop, you immediately continued...
When I reviewed the conversation later that day during the start of my shift, I made the decision to ban you.

Just because you don't see the point in recipe chains in certain packs, doesn't give you the right to sit there, throw insults, snide remarks, passive-aggressive commentating, and, generally: Being a dick.
You were being toxic and you broke Wheaton's Law - The fact you can't see that, does not make me want to un-ban you.
