### ISSUE TITLE
I was stupid and would like to be unbanned

### ISSUE THREAD

**Issue by Scotchleaf** [CreeperHost/CreeperHostGui#314]
**Minecraft Username:** 
Scotchleaf
**Ban ID:**
It didn't say, I just got reported then banned for language
**What was the reason for your ban?** 
Somebody said d*ck and b*lls and  was muted for five minutes. Jokingly, I said "Who doesn't love a good d*ng*s", A user, taken aback with the horrendous filth spewing forth from my lips then reported me. 

**Why you think you should be unbanned:**
Because it's not actually a swear word, and I didn't know the word criteria for being banned was so strict.

**What steps will you take to make sure this doesn't happen in the future:**
Mind my tongue even more.

**Comment by Draylynn** [comment]
You know what's harsh, having to attend the chat almost 24/7 because kids, teens and adults, do not have an inkling of respect or consideration for anyone else in the public chat, but themselves... And in the year 2020 of all things, it's disgraceful.

You got reported for being explicit and mentioning male genitalia, the fact you did this straight after, and knowingly, seeing another user get banned for the _same thing_, is just adding salt to the wound. You knew very well what you were doing and what context you were displaying.
Lewd behaviour is entirely inappropriate in this chatroom, it sets a bad example to the young users and reinforces bad behaviour.

This isn't Fortnight, WoW, COD etc, where the moderators don't really give two sticks about general conduct until they hit the headlines. This is MineTogether cross-modpack chat, a gaming chatroom, and by'gum, people will behave or get the fudge out. Try your appeal again later (min. 30 days), maybe by then you'll better understand etiquette and civility.

And don't go blaming the users for reporting people, they're ensuring the chat stays clean and Christian, we added the feature for that reason (should a mod be somewhat inattentive to chat for periods of time, users can get their attention).

[Kicks into the void]
**Denied.**
