### ISSUE TITLE
I was stupid and would like to be unbanned 

### ISSUE THREAD

**Issue by LOC21** [CreeperHost/CreeperHostGui#317]
**Minecraft Username:** 
LOC20
**Ban ID:**
I couldn't find this!!
**What was the reason for your ban?** 
I said an inappropriate russian word

**Why you think you should be unbanned:**
I thought since it was russian that it wouldnt count as swearing, I now realise that this makes it worse, because the chat is English only

**What steps will you take to make sure this doesn't happen in the future:**
I will think about the message that i have written before i send it to chat.

**Comment by LOC21** [comment]
I would like to add that I do not deny that I broke the rules, and I think I deserve the ban, but I just don't think it should be permanent.

**Comment by Draylynn** [comment]
"I thought since it was Russian that it wouldn't count as swearing"

...Eh... What? _[Visible confusion]_
Swearing is swearing, whether it's said straight up, in another language or obfuscated. Pretty sure the rules say at the start of chat (or by being told to type 'rules'), quite clearly: "**No Swearing**"
Contrary to popular belief, this actually means **no use of vulgar language at all**, it's not rocket science, it's basic etiquette.
Then to add insult to injury, the context of its use was entirely toxic, which is a breach of Wheaton's Law.

There are kids and adults in this chatroom, all over the world, which is ESRB 10+:  You should set a good example and communicate amicably, you did not.

You aren't getting un-banned today, for sure. Sometime between now and the end of this month, _maybe._

Your punishment will be loading up MC everyday, and praying the ban fell off... It will feel like an eternity, and each time you're met with "Disconnected, reason: banned", you'll reflect on this - Hopefully by the time you do actually get in, it will be so subconsciously burnt into your soul, you'll think twice next time.

**Comment by LOC21** [comment]
yep that's fair. Thank you!
