### ISSUE TITLE
I was stupid and would like to be unbanned

### ISSUE THREAD

**Issue by BlandGenericCG** [CreeperHost/CreeperHostGui#321]
**Minecraft Username:** 
BlandGnericCG
**Ban ID:**
don't remember but my unique code is: RvQn-NRdj and happened around 7pm central 8/14/202
**What was the reason for your ban?** 
Inappropriate language

**Why you think you should be unbanned:**
I said "Downs syndrome is caused by an extra "sex" chromosome." so I don't think it was inappropriate per say, but I get why the ban happened.

**What steps will you take to make sure this doesn't happen in the future:**
it was more so an accident so just being more careful as to not use words that may be flagged even if not used in an inappropriate way.
thanks and sorry for the inconvenience

**Comment by Draylynn** [comment]
The ban happened because the bot is programmed to ban on detection of certain words or phrases. 'Sex' happens to be one of them, because 90% of the time, it's incorrectly used.
Also, the topic being discussed was borderline - Would have only taken 1 idiot to likely at least 4 of you banned.
Remember this is a gaming chatroom, ESRB 10+.
