### ISSUE TITLE
I was stupid and would like to be unbanned

### ISSUE THREAD

**Issue by Playbahnosh** [CreeperHost/CreeperHostGui#323]
**Minecraft Username:** Playbahnosh

**Ban ID:** I didn't get one? 

**What was the reason for your ban?** All I saw was my messages were purged and then I got disconnected without any message. I don't remember saying anything inappropriate. I can only guess, but I think it was the old Avenue Q song I linked. We were talking about old memes, and "The Internet is for Porn" is a classic. It's not an explicit song by any means, aside from the word "porn" in it, but I guess even that is not allowed.

**Why you think you should be unbanned:** I honestly didn't mean to offend anyone. I was really having fun talking to others and even helping them out with their problems. But I do apologize for posting that song if that was the issue.

**What steps will you take to make sure this doesn't happen in the future:** I guess won't be posting any links in the future.

**Comment by Draylynn** [comment]
It is a classic, it's funny.... I agree, for adults. But it's not appropriate for a children's chatroom. Incoming harsh grilling...

The entire parody is based on using the internet, for porn... Which on the internet, is for the most part, especially twisted, malformed and incorrectly displayed. "Oh porn, what is that?", do you know how much mental damage a Google search for this term can do to a kid? The unrealistic expectations it sets? Do you realise how many people are growing up emotionally/mentally screwed up because of porn?

**You don't expose young underdeveloped minds who don't fully understand, to it.** Full stop, and it certainly isn't your place to educate kids about it, that's up to parents.

Think before you share things, especially in a public chatroom on an age-rated game, because you can do a lot more than simply 'offending' people - Communication is a **powerful** skill we have developed over the millennia, pay attention to it, use it properly, check what you're actually communicating is suitable for the recipients.

The ban will fall off, but I won't tell you when. Keep checking everyday, each time you see "Banned", reflect on this, maybe you'll learn something.
