### ISSUE TITLE
Allow filter to be turned off clientside

### ISSUE THREAD

**Issue by TheYeti** [CreeperHost/CreeperHostGui#37]
The filter is slightly....draconian to say the least and extremely ineffective.  When talking about minecraft related subjects it often filters words arbitrarily that disrupt the conversation.  Like telling someone to plant sugarcane on snad results in "plant sugarcane on s***".  Which ends up just being confusing and making it sound worse than it is.

Also, this wasn't implemented in a case insenstive way so SNAD will bypass the filter but snad will not.

**Comment by CH-Paul-T** [comment]
I believe the case-sensitive nature may have been a bug brought around by partial disablement, I had tried to turn off the filter as it had proven ineffective in doing anything except hinder normal communication, but an API syncing bug had caused mismatches around the globe, this has since been resolved.

Please let us know if you're still encountering issues.

**Comment by Cloudhunter** [comment]
Closed as "fixed" by having no filter.
