### ISSUE TITLE
Add an "Accept Terms" step when joining Global Chat for the first time

### ISSUE THREAD

**Issue by jagrider** [CreeperHost/CreeperHostGui#377]
**Is your feature request related to a problem? Please describe.**
FTB recently added the MineTogether (MT) mod to their packs, and thus FTB players are seeing the MT Global Chat for the first time. Many of them are thrown into the chat, and react with things like "wtf" or "who the (expletive) are you guys" and get banned right away as they don't know the rules. I imagine this happens to a lot of modpack players, not just FTB players.

___________________
**Describe the solution you'd like**
When a user accesses MT Global Chat for the first time, they should not be able to see messages from other users until they:
- have the rules clearly displayed on their screen _without any interruption_ [1], and
- type `/accept <username>` or an equivalent acceptance statement into their Minecraft chat or user interface [2]

This would help reduce the number of unneeded bans simply because people don't understand (or even know of) the MT Global Chat rules. The user provides their name as a way of affirming that they themselves are accepting the rules (and this could be stored somewhere to signify that this specific user accepted the rules).

Additionally, any time the rules are updated, users could (or should) be asked to accept the updated rules. This prevents any chat user from being out of the loop in terms of the rules.

[1] On some machines, the MT Global Chat system message will not appear in the feed as the chat has loaded before the user can access it. Chat messages from other users will push the system message out of view and sometimes outside of the in-game chat's cache.
[2] An alternative method to confirming their understanding and acceptance of the rules could be a UI "checkbox" and confirm button

__________________________
**Describe alternatives you've considered**
1. **Requiring users to link their Minecraft account to a Discord and/or MineTogether.io account in order to access the MT Global Chat**
    - This would increase the chance that users will fully understand the rules before joining, but could reduce the amount of users who are able to use and/or want to use the service. 
    - Additionally, for privacy reasons some users may not want to link their Minecraft account with external entities.

2. **A MineTogether Tutorial book that explains what the mod is, how to use it and the rules within the MT Global Chat. Users must click a button on the last page of the book to gain access to the MT Global Chat**
    - I worry that many users do not read modpack books, especially veteran players who are familiar with most if not all mods in the modpack(s) they play
    - This would provide more of a "tutorial" based understanding of the rules and would be a better approach than the System messages that first appear when loading up a Minecraft game/server (see [1] above)

3. Change nothing
    - This is a non-solution and should not be considered, as it leaves the underlying problems to persist. 

___
**Additional context**
Without implementing this feature/enhancement, I think giving out a permanent ban on the first violation is a bit harsh. While the core Minecraft game is rated ESRB 10+, _**online interactions are not**_. 

Anyone who plays on a Minecraft server knows that chat rules vary between servers, and therefore it is not fair to permanently ban someone on the first offense when they don't even know they are making an offense. Obviously there are some extreme circumstances where exceptions may apply (E.g., racial slurs), but the vast majority of violations I have seen are comparatively "minor" in terms of offensiveness. 

Messages in violation should be forcibly removed, but not necessarily the user.

**Comment by ThePaul-T** [comment]
Hello,

Bear with me here, as it's 3 am and some of these replies may not be perfect, but I will try and address your points.

1) MineTogether has been in FTB packs for nearly three and a half years.
2) Would you walk up to a group of strangers on the street and immediately start swearing at them? This is a terrible excuse and encourages me further to not implement anything.
3) Text commands are a no-go where not absolutely necessary, it breaks user flow.
4) We've been toying with a UI.
5) Your "Change nothing" response make me feels like you can dictate changes to us, rather than suggest them, was not necessary to even be included and has made me immediately close this on principle.
6) Just because Minecraft's core functions are not rated at ESRB 10+, MineTogether chat strives to be, not sure why you needed to include this in the context, seems like you're just trying to question our reasoning.
7) Because chat rules vary, doesn't mean, once again, you can go in swearing and using racial slurs until told otherwise, that is like suggesting no laws are to be followed until a police officer tells you it's against the law.

We take a very hard approach on this due to the inherent toxicity of online gaming communities, when not harshly moderated, they turn into pools of toxicity very quickly. Nobody has the right to use MineTogether chat, and we remove anyone who will not behave by our rules early on.
We have an appeals system, so anyone who cares enough and has not given us loads of reasons not to usually gets unbanned these days.

**Comment by jagrider** [comment]
Hello! Thanks for the response.

Firstly, I want to apologize for any offense I have made or for making any indication that I am in a position to dictate your decision/development process. I did not intend to come off in this light and I absolutely see now how it would be taken that way. I really tried to put a lot of thought into writing this Issue but that is no excuse for my assertiveness and obsessive desire to be verbose. Again, I apologize for this and for not realizing it sooner.

1. Apologies for the confusion, I recently received client updates for several FTB modpacks which solely added MineTogether (some of which hadn't been updated in years), and I had not seen it in packs I had previously played. If it has been in others, then that can obviously be disregarded as a misunderstanding on my part. Regardless, I did not mean to focus this only on FTB modpacks.
2. No I would not.
3. I favored the text command approach as I thought it could prove more likely that a user would have read the rules (or at least had a chance to) before joining the chat. From my personal experience, The chat showed up and I saw messages and not the rules. Only after the first few times I opened my singleplayer save did I see the system message with the rules. That is part of why I filed this.

5. Regarding point 5, Please see my note above.
6. I included this because of discussion I saw in the MT global chat between some users and a moderator. The moderator's replies seemed to indicate the rule was in place _because_ Minecraft is ESRB 10+, rather than because MineTogether strived to be that way. I did not mean to offend by including this, and I should have also included this context in the original Issue filing.
7. Totally understand this viewpoint, and I do not condone stepping into a scenario and spewing racial slurs or foul language. I also don't condone breaking the law until it has been stated before you. But this is besides the point of me filing this Issue: from my experience (and, based on the chat, experience of others), the rules are not always clearly visible.

**Comment by ThePaul-T** [comment]
Okay, that is fine.

FYI, I have been toying with the idea of a UI. I don't like text commands as people seem to struggle reading them to use them.

The UI approach comes with the issue of "lets click it without reading"...

So at the moment, it's been left-as-is until we come up with a solution... We're also thinking of perhaps sending a CTCP event on the IRC server (to the bot) the first time the chat tab is selected, and sending the rules again then... As at the moment we have no way to detect when a user is actually in the chat, only when they join.

I appreciate you making a report, so don't let it discourage you, but we honestly get a lot of push back on the rules, I've worked on MMO platforms since I was 13 (19 years ago, I'm getting too old for this), including developing C/C++ MMO emulators, I have seen so many communities become so bad, and I don't want to even be associated with that if it happens here.

It makes me quite defensive over it... We should have a solution in the next few weeks which helps with this issue.

**Comment by ThePaul-T** [comment]
Latest versions of the mod send us a CTCP "ACTIVE" message the first time someone opens the tab in each game "session" now, and that is when we send the rules.
