### ISSUE TITLE
Chat not working

### ISSUE THREAD

**Issue by RagemageTuur** [CreeperHost/CreeperHostGui#482]
**Describe the bug**
My chat suddenly stopped working. I can't send any messages and I can't see any either.

**To Reproduce**
/

**Expected behaviour**
I expected to be able to use the chat.

**Versions**
Please give all the versions you are using:

Minecraft:
1.12.2

Forge:
14.23.5.2846

MineTogether:
2.4.1

**Additional context**
None specifically

**Comment by gigabit101** [comment]
Can you provide us with the logs?

**Comment by uecasm** [comment]
FWIW, I have this happen as well whenever I have a long swapspike (MC goes unresponsive for a minute or two).  Presumably the server connection is timing out, but there is no automatic reconnection.

I can recover from this if I go into the menu, tell it to disconnect (yes, it thinks it's still connected there), then tell it to connect again.  But I shouldn't need to do this (and it's inconvenient since I can't do it without going back to the main menu).

**Comment by gigabit101** [comment]
Should be fixed in the latest release
