### ISSUE TITLE
Crashing when loading Stoneblock 2 world

### ISSUE THREAD

**Issue by NKnueppel** [CreeperHost/CreeperHostGui#486]
I have well over 100 hours in Stoneblock 2 and have not had any issues until today. Now any attempt to load my world results in a crash and Mine Together is supposedly the issue. I have tried repairing the profile through the Curse launcher, but it did not fix the issue. Attached is the crash report.

[crash-2021-01-18_13.32.13-server.txt](https://github.com/CreeperHost/MineTogether/files/5832300/crash-2021-01-18_13.32.13-server.txt)

**Comment by meltingzero** [comment]
I get the same error. Note that there has been a thread in which it was said that this particular issue has already been fixed, dating 2019. But it's still (or again) occurring. Here is said thread: https://github.com/CreeperHost/MineTogether/issues/61
NKnueppel, you should try what the thread says for fixing the crash issue, I will do the same momentarily.
It said "You will need to delete the Minetogether config from the configs folder." and one user reported that after deleting the MineTogether mod folder a couple of times, they could open their world again.

Here is an image of the crash message the way it shows itself for me:

![image](https://user-images.githubusercontent.com/77793625/105369183-9a19bc80-5c02-11eb-985e-720d40bf99ad.png)





EDIT: I made it work with the instructions, so here's how.

I didn't know where Stoneblock 2's directory was, so here is where it was for me if anyone else has trouble finding it:
user/documents/curseforge/minecraft/Instances/FTB Presents Stoneblock 2/

There, in the /config folder, I deleted the .cfg file of minetogether (the mod didn't have a separate folder in that directory, so it's with the individual .cfg files down below the folders). After deleting and restarting Stoneblock 2, the error still appeared.

Then, instead of /config, I went to /mods and found the minetogether folder. So I deleted that, restarted the game, and now it works.

Here are the first and last crash file if that's of any use. I have, like, eight from the same error, so request them on a needed-basis.
[crash-2021-01-21_15.38.41-server.txt](https://github.com/CreeperHost/MineTogether/files/5850392/crash-2021-01-21_15.38.41-server.txt)
[crash-2021-01-21_16.22.00-server.txt](https://github.com/CreeperHost/MineTogether/files/5850393/crash-2021-01-21_16.22.00-server.txt)


Cheers

**Comment by gigabit101** [comment]
remove the MineTogether config file and restart the game, Not sure what is causing this but will see if I can patch it our side
