### ISSUE TITLE
Issue/question about [Community] Tag.

### ISSUE THREAD

**Issue by AndersWithTheCat** [CreeperHost/CreeperHostGui#50]
Hi so i got tow of the same mod pack(stoneblock 2) runnning on one machine and not the second(newest) server got a perm added [Community] In the Tag line. i don't see any config option to disable it, or anything. please let me know how to remove or if there can be a fix?

**Comment by CH-Paul-T** [comment]
Hey there,

At the moment is a very "dumb" method at our end of trying to guess which servers require/request sign ups to a community (discord or otherwise) to be able to play.

This will be changing in a version released soon to a proper UI expressing this and that tag removed.

The way to remove it would be to ensure there's no URL's or the word "whitelist" in your server description.

We do this because trying to join a publicly listed server to be presented with a whitelist screen is bad for the end user UX, and until we have a proper UI update (@gigabit101 is almost done with my requested changes), this was the easiest way to implement.

Regards,
Paul

**Comment by AndersWithTheCat** [comment]
Well funny enough. its the public server that got the community tag haha:) my whitelisted community server is without that community tag? :/ 
oh well ill guess it can get reset with a change of port or something :)

**Comment by CH-Paul-T** [comment]
Yeah, we ran into the issue that without writing our own client emulator, there isn't a reliable way to  get the whitelist status of a server... So we rely on little 'keys' in the motd/description etc and take a best guess.

The  next version will accommodate these servers properly with a "Click to Apply" button and similar to streamline the whole process for these servers.
