### ISSUE TITLE
More transparency/accountability in bans

### ISSUE THREAD

**Issue by ElBiggus** [CreeperHost/CreeperHostGui#516]
**Is your feature request related to a problem? Please describe.**
See bug report about mysterious ban.

**Describe the solution you'd like**
When the system decides to ban you it ought to *say* that's what has happened - the current "it just stops working" deal is unhelpful as it gives no indication that you've been banned, why, or how and where to appeal. The account standing page really also needs to show details of previous bans, and if a ban is lifted because it was done in error it shouldn't count towards "you've previously been in poor standing" - that's like being accused of a crime, being found innocent, and still having a criminal record.

**Describe alternatives you've considered**
I have a long laundry list of terrible UI/UX design choices, so don't get me started!

**Comment by combustor** [comment]
nobody cares about you
the mods have large egos
i asked a simple question and got a whole essay and then said "what the fuck" and instantly got banned
(this happened while russians were also talking which is against the rules but large egos + moderating = retardation)

**Comment by ThePaul-T** [comment]
@godspeedfunnyman 
No large egos, you got banned by the bot because webpurify's web API automatically detected an expletive.

But now you've done this here, we know who you are, so don't bother appealing.

When I get time to review @ElBiggus's message and give it the time it deserves, as it seems to be more thought out than most, I will, but I do not yet and I am not going to rush, as it sounds like they are actually pointing out issues I am already aware of regarding the "flow" for bans.

**Comment by Draylynn** [comment]
"the current "it just stops working" deal is unhelpful"

Didn't we have a disconnection message previously?
Now chat just drops dead on the spot: Users don't know if they've been banned, or there's been a malfunction in their client, it comes up a lot in MT chat.
One person who thought they were banned for 3 days, turned out to be a connection issue that wasn't printing to the chat tab for some reason, where other users have had the opposite issue.

Lil' OCD about the ban count on the profile myself, but at the same time: How many times you got banned, doesn't really factor into anything, it's just history, whether it was accidental or intentional. All bans are recorded so we can check they were correctly applied or find them if we need to investigate them.
That being said, I don't like the "Previously in poor standing"... Let's move forward... [Shakes MineTogether.io profile page] Faaarrrwaaard!

**Comment by Draylynn** [comment]
Ban appeals are made on MineTogether.io - Do not usurp other peoples issue postings.

**Comment by Abtinestor** [comment]
Omg im so sorry, im new to github and thought its a public section, ill delete it
But before that can you tell me other than minetogether.io where can i request for a unban cus i have appealed there months ago (it was my first ban) but didnt got accepted

**Comment by gigabit101** [comment]
You should now see a message in your text box showing that you are banned
