### ISSUE TITLE
Potentially banned? Unsure

### ISSUE THREAD

**Issue by Redayez** [CreeperHost/CreeperHostGui#532]
I was having a conversation about World of Warcraft with staff member while playing in my solo FTB world. There was nothing vulgar or inappropriate said; all pg I would say; however, suddenly I was unable to send chats and it was as if the chat died. I attempted to restart my Minecraft to no avail. I went to the MineTogether site and it said apparently I am in good standing for global chat, but I have had 1 ban--which I do not recall at all. I'm very confused. It says I am not banned, but was once--I don't even remember that.

My Minecraft username is RedayezJr

**Comment by Draylynn** [comment]
User name is useless, we don't see your MC name. I do have a vague memory of a WoW discussion and someone slipping up and getting banned midway through.
What is your MineTogether ID (on MineTogether.io)? I can try to use that to locate any ban.

**Comment by Redayez** [comment]
Thank you for the response.

My MineTogether ID is User#86F51

The ban is now show in on MineTogether, so I will go ahead and appeal it there now--just in case you still would want the ban info, here it is:

ID: mtg-ban=60b5f3dae5f6a0.41263385
Reason: Banned
Moderator: draylynn
Message: p1622534669491700

**Comment by Draylynn** [comment]
For some reason, during a discussion of what is acceptable or not and previous bans, you decided to contextually relate to a previous offense and indicated to other users the use of vulgar language.
"No vulgar/offensive language" its the rules.
Just because the language is obfuscated does not negate the fact you are still relaying it... Communication, it's a simple concept.

Bare this in mind in future.
