### ISSUE TITLE
[Suggestion]: Allow me to use normal chat

### ISSUE THREAD

**Issue by Bennyboy1695** [CreeperHost/CreeperHostGui#624]
### Is your feature request related to a problem? Please describe.

I just launched a pack with the minetogether mod installed was asked if i wanted to join the minetogther chat network to which i clicked the no option (unsure of the wording exactly) which then disabled me from using the normal ingame chat.

### Describe the solution you'd like

When disabled i would like the chat to go back to the default chat system

**Comment by shinji257** [comment]
This is likely a bug.  If you disable the MineTogether chat manually while on the server it shuts itself off and leaves you on server chat but once you restart the game it goes back to the MineTogether tab which doesn't work because it is disabled.  The game also crashes if you try to type in the (now disabled) chat.

**Comment by shinji257** [comment]
Pack: Stoneblock 3
Version: 6.0.7

**Comment by covers1624** [comment]
The root issue here has been resolved in dev.

**Comment by covers1624** [comment]
This has been fixed in MineTogether 6.0.8. Pending review on CurseForge.
