### ISSUE TITLE
Banned from MineTogether(Not sure where I would normally put this)I

### ISSUE THREAD

**Issue by LegalizeLolis** [CreeperHost/CreeperHostGui#65]
I was banned from MineTogether today because I said "I'm basically drinking from the tit of the coffee fairy" and was banned without being warned.(Mind you, I was told the rule and I apologized, but was immediately banned, with this being my first offense).

**Comment by CH-Paul-T** [comment]
Hey there,

Just to put a reply here.

We saw this and Draylynn was going to unban you, then it turns out you decided to go onto unrelated git pages and start replying to issues opened on unrelated projects to get unbanned.

That is not acceptable, you've put something unrelated in a third partys git issue tracker and are borderline harassing the staff running this.

I have left standing notes to all staff to never unban you.

Paul
