### ISSUE TITLE
[Bug]: Unable to appeal ban

### ISSUE THREAD

**Issue by derpendary** [CreeperHost/CreeperHostGui#719]
### Describe the bug

Unable to appeal ban on Minetogether website 

### Steps to reproduce

1. Go to Minetogether.io
2. Click on profile
3. Click account standing

### Expected behaviour

Able to click on and engage in the ban appealing process.

### Version

N/A

### Minecraft Version

N/A

### ModLoader Version

N/A

### Additional Information

I don't know where else to file this, as there are no alternative means of contact that I could find.

**Comment by Draylynn** [comment]
Do you have a ban ID so we can check the ban?

**Comment by ExNando** [comment]
Hello Draylynn, I made a ban appeal, recently I was banned for some reason regarding rules I think and it was unintentional. It's probably because I spoke another language in the chat but as soon as I was notified I stopped. I would like you to read my ban appeal.

BAN ID: mtg-ban=64d05ab7281086.87315527

**Comment by Draylynn** [comment]
Do not hijack other peoples posts. Ban appeals are handled on MineTogether.io - If your ban was denied, try again in up to 2 weeks.
